[[redirects]]
  from = "/api/*"
  to = "https://backend.knitandpearl.online/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
